<?php

$titre = "Accueil: Age D'olmes";

$content = "TexLorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut mi eu tellus tempor convallis in id elit. Ut luctus libero in mi pulvinar, nec porta turpis dapibus. Vestibulum quis urna facilisis urna vestibulum dapibus vitae et ex. Donec sit amet ante non sapien scelerisque mollis. Integer varius eu massa in volutpat. Maecenas pharetra eu tortor non sodales. Sed a pharetra augue, id laoreet leo. Mauris laoreet quis arcu at efficitur. Nullam quis quam ullamcorper, aliquet nulla eget, scelerisque felis. Phasellus pretium dui non risus finibus, sit amet congue magna eleifend.

Mauris at varius orci. Nulla volutpat enim nec libero sagittis, vitae congue leo finibus. Donec consectetur lacus urna, et varius odio facilisis eu. Fusce tincidunt enim vel mattis molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam vestibulum ultrices libero non rutrum. Nunc sit amet mauris sem. Sed felis lorem, eleifend a lorem ac, mollis egestas est. Mauris metus orci, pellentesque vitae varius id, pellentesque eu neque. Integer at porttitor libero. Quisque at felis magna. Integer venenatis odio vitae lacus pellentesque pulvinar.

Nulla vitae mi finibus, accumsan ipsum pharetra, venenatis turpis. Pellentesque efficitur quam neque, a commodo lorem ultricies in. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec sed interdum diam. Duis a sodales massa, a ornare magna. Sed ullamcorper metus vel imperdiet consectetur. In suscipit eget dui ut volutpat. Aliquam dictum ligula justo, sollicitudin suscipit enim tempor eget. Morbi ultricies lectus eget suscipit bibendum. Mauris eu risus in justo scelerisque efficitur.

Fusce massa nunc, elementum nec bibendum sit amet, varius id massa. Nulla gravida, ante ut molestie tincidunt, dolor magna tempor arcu, ac tristique quam tellus pellentesque tellus. Phasellus facilisis pharetra euismod. Mauris enim sapien, porta et molestie nec, viverra vel quam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus ultrices ante pharetra, venenatis ligula eu, rutrum felis. Duis venenatis tincidunt pharetra. Fusce nec nisi orci.

Suspendisse nec diam nulla. Quisque ornare tincidunt ornare. Maecenas tempus tincidunt arcu, ut cursus massa posuere a. Cras dapibus egestas lectus, eu lacinia enim laoreet ut. Etiam sit amet est aliquam, feugiat nibh id, bibendum nisi. Curabitur congue lobortis fermentum. Vestibulum a arcu tempus, suscipit sapien et, accumsan est.

Nullam vel justo quis quam congue imperdiet. Fusce diam nisl, euismod et nulla eget, venenatis rhoncus augue. Maecenas fermentum ligula sed porttitor ullamcorper. Nunc vel nibh et arcu ultrices vulputate. Morbi dignissim, dolor sit amet vulputate pharetra, leo nisl luctus sapien, eget porttitor tortor lorem et ipsum. Ut rutrum tellus quis turpis congue iaculis. Nullam rhoncus sollicitudin ipsum vel lacinia. Etiam sed tempor massa.

Nam vulputate ex et gravida vehicula. Donec eget mauris mi. Sed nec sem vel dui porttitor auctor eget sit amet lacus. Vivamus cursus odio scelerisque, ornare mi quis, pharetra mi. Ut cursus elit sapien, ultricies tempor felis placerat eu. Maecenas vel ante egestas, faucibus elit eget, vehicula velit. Curabitur nibh dolor, luctus sed hendrerit ac, porttitor et diam. Donec placerat consectetur consequat. Ut semper dictum nunc eu congue. Nulla pellentesque placerat tempor. Nullam nec lectus sed lectus varius gravida. Aenean sed metus non nulla aliquam lobortis eu a libero. Phasellus pharetra nisl quam, aliquam sollicitudin orci tempus eget. Donec tincidunt sagittis justo vel scelerisque. Quisque a lacinia mi. Nulla facilisi.

Maecenas aliquam, erat at scelerisque tristique, neque ligula accumsan leo, ac cursus magna leo sit amet arcu. Curabitur vitae nulla arcu. Suspendisse tincidunt, arcu id maximus interdum, lorem erat sagittis diam, ac eleifend nisi felis in sapien. Quisque faucibus turpis a leo aliquam, sed viverra augue hendrerit. Sed maximus volutpat leo, gravida mattis quam sollicitudin in. Integer ultricies mauris volutpat, venenatis orci eget, pellentesque urna. Aenean urna felis, placerat nec fringilla et, egestas sed nulla. Etiam eu ipsum consequat, porta libero ac, tristique lectus. Nunc varius nisi vel purus pulvinar viverra id nec lorem. Vivamus luctus eros non augue tempor porttitor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse gravida tincidunt erat, pulvinar viverra erat vulputate vitae.

Ut consequat sem porttitor, fermentum odio eu, condimentum mauris. Mauris malesuada ultrices ante a tincidunt. Ut posuere dolor urna, ac consequat odio porta sit amet. Pellentesque mollis lacus eu mauris cursus consequat. Ut dictum arcu ac lectus auctor, at bibendum turpis feugiat. Fusce ut interdum ipsum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse ornare in arcu at rutrum. Donec sagittis porttitor nulla, sed sagittis purus volutpat nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Cras mollis tortor sapien, sed euismod urna consectetur vitae. Sed ac tempus nisi, blandit scelerisque metus. Donec vehicula diam dolor. Cras fringilla id turpis sit amet congue. Pellentesque sed nulla posuere, tristique sapien eget, sollicitudin nisi. Suspendisse vulputate volutpat ante, a hendrerit justo fringilla accumsan. Sed at varius odio. Sed mollis magna non magna condimentum semper. Nulla eget congue sapien, eget iaculis neque. Curabitur vel eleifend ante. Donec consectetur malesuada velit, id pellentesque diam. Nunc turpis sem, aliquet vel interdum vel, maximus sed justo. Sed fermentum, augue a condimentum faucibus, dolor odio mollis ante, nec vestibulum ipsum ligula sed erat.t";

require_once ("../vue/Layout.php");